/* Configuration for simple_logging generated by Alire */
#ifndef SIMPLE_LOGGING_CONFIG_H
#define SIMPLE_LOGGING_CONFIG_H

#define CRATE_VERSION "1.3.0-dev"
#define CRATE_NAME "simple_logging"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
